Add tflint/run rule
awslabs/aws-code-habits pull request #7
Opened 2022-12-14 07:51 UTC by DavidS-om

This is required for terraform/init. See https://github.com/awslabs/aws-code-habits/blob/2cb972c53a246c0d5cba8b4d2a0f22e604eb7008/lib/make/terraform/Makefile#L6

2022-12-15 08:11 UTC, valter-silva-au requested changes

2022-12-15 08:11 UTC, valter-silva-au commented on lib/make/tflint/Makefile
> +	@tflint .
Would you mind fixing the identation @DavidS-om ?

2022-12-15 12:09 UTC, DavidS-om commented on lib/make/tflint/Makefile
> +	@tflint .
It's indented by one TAB char. Is that not correct?

2023-01-05 02:35 UTC, valter-silva-au approved these changes

2023-01-05 02:35 UTC, valter-silva-au commented on lib/make/tflint/Makefile
> +	@tflint .
I believe your tab has 8 spaces. We're using 4 spaces per TAB.

2023-01-05 02:36 UTC, merged